# Generated by Django 5.1 on 2025-03-02 15:07

import reserv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('table', models.IntegerField(validators=[reserv.models.max_valid_check])),
            ],
        ),
    ]
